# Chapter 4

# 4.4.1. Normalization and standardization

Normalization

Min-Mx scaling 

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
# Sample data
data = {
    'Age': [25, 45, 30, 60, 35, 75],
    'Income': [50000, 120000, 80000, 100000, 60000, 150000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
# Initialize MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
# Fit and transform the data
normalized_data = scaler.fit_transform(df .to_numpy())
# Creating a new DataFrame for the normalized data
normalized_df = pd.DataFrame(normalized_data, columns=df.columns)
print("\nMin-Max scaling:")
print(normalized_df)


Original DataFrame:
   Age  Income
0   25   50000
1   45  120000
2   30   80000
3   60  100000
4   35   60000
5   75  150000

Min-Mx scaling:
   Age  Income
0  0.0     0.0
1  0.4     0.7
2  0.1     0.3
3  0.7     0.5
4  0.2     0.1
5  1.0     1.0


MaxAbs scaling

In [4]:
import pandas as pd
from sklearn.preprocessing import MaxAbsScaler
# Sample data
data = {
    'Prameter 1': [-5, 0, 7, 4, 1, 4],
    'Prameter 2': [4, -12, 6, 3, 2, -5]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
# Initialize MinMaxScaler
scaler = MaxAbsScaler()
# Fit and transform the data
normalized_data = scaler.fit_transform(df .to_numpy())
# Creating a new DataFrame for the normalized data
normalized_df = pd.DataFrame(normalized_data, columns=df.columns)
print("\nMinAbs scaling:")
print(normalized_df)

Original DataFrame:
   Prameter 1  Prameter 2
0          -5           4
1           0         -12
2           7           6
3           4           3
4           1           2
5           4          -5

MinAbs scaling:
   Prameter 1  Prameter 2
0   -0.714286    0.333333
1    0.000000   -1.000000
2    1.000000    0.500000
3    0.571429    0.250000
4    0.142857    0.166667
5    0.571429   -0.416667


Standardization 

Z-score 

In [5]:
import numpy as np
from sklearn.preprocessing import StandardScaler
# Example data
data = np.array([[10, 2.7, 3.6],
                 [15, 3.0, 9.0],
                 [16, 2.5, 5.5],
                 [18, 3.2, 6.8]])
# Create a StandardScaler object
scaler = StandardScaler()
# Fit and transform the data
standardized_data = scaler.fit_transform(data)
print("Standardized Data:\n", standardized_data)

Standardized Data:
 [[-1.61155897 -0.55708601 -1.33576544]
 [ 0.08481889  0.55708601  1.41209489]
 [ 0.42409446 -1.29986737 -0.36892569]
 [ 1.10264561  1.29986737  0.29259624]]


Robust scaling

In [6]:
import numpy as np
from sklearn.preprocessing import RobustScaler
# Example data
data = np.array([[10, 2.7, 3.6],
                 [15, 3.0, 9.0],
                 [16, 2.5, 5.5],
                 [18, 3.2, 6.8]])
# Create a StandardScaler object
scaler = RobustScaler()
# Fit and transform the data
standardized_data = scaler.fit_transform(data)
print("Standardized Data:\n", standardized_data)

Standardized Data:
 [[-2.         -0.375      -1.09677419]
 [-0.18181818  0.375       1.22580645]
 [ 0.18181818 -0.875      -0.27956989]
 [ 0.90909091  0.875       0.27956989]]
